### ISSUE TITLE
Config to change number of databases in Redis

### ISSUE THREAD

**Issue by jklemm** [zhulik/redis-action#1]
Will be nice if have an option:

    number of databases: NUMBER

I have a lot of python tests, and to work well I need change the number of databases in `redis.conf`.

Is there a way to do that today?

**Comment by zhulik** [comment]
Hey, @jklemm! I'm not sure about today, but I hope I'll find some time on the weekend

**Comment by zhulik** [comment]
Hey, @jklemm Please, check the latest version

**Comment by jklemm** [comment]
WOW!! Thanks a lot, I will test right now!

Hmm, in the README.md, it's documented to use this way:

```
- uses: zhulik/redis-action@v1.1.0
```
Using this way cause GH Actions error:

```
##[warning]Failed to download action 'https://api.github.com/repos/zhulik/redis-action/tarball/v1.1.0'. Error Response status code does not indicate success: 404 (Not Found).
##[warning]Back off 13.777999999999999 seconds before retry.
```

But the correct way it's without the `v` on version.

```
- uses: zhulik/redis-action@1.1.0
```

**Comment by jklemm** [comment]
Very nice! It works with version `zhulik/redis-action@1.1.0`, without `v` in version.

You can close this issue.

Thanks a lot!

**Comment by zhulik** [comment]
@jklemm Thank you! I've just update the version string in the readme.
